CLM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myclm.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

myclm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path
from myclm.views import *

app_name = 'myclm'
urlpatterns = [

    path("", homepage, name='homepage'),
    path('home_member/', views.home_member, name='home_member'),
    path('home_staff/', views.home_staff, name='home_staff'),

    path("staff-login/", staffLogin, name='staffLogin'),
    path("member-login/", memberLogin, name='memberLogin'),

    path("staff-signup/", staffSignup, name='staffSignup'),
    path("member-signup/", memberSignup, name='memberSignup'),

    path("logout/", user_logout, name='user_logout'),

    re_path(r'^home/$', views.home, name='home'),
    path('member_list', views.member_list, name='member_list'),
    path('member_list_staff', views.member_list_staff, name='member_list_staff'),

    path('member_staff/create/', views.member_new_staff, name='member_new_staff'),

    path('member/<int:pk>/edit/', views.member_edit, name='member_edit'),
    path('member_staff/<int:pk>/edit/', views.member_edit_staff, name='member_edit_staff'),

    path('member/<int:pk>/delete/', views.member_delete, name='member_delete'),
    path('member_staff/<int:pk>/delete/', views.member_delete_staff, name='member_delete_staff'),

    path('borrow_list', views.borrow_list, name='borrow_list'),
    path('borrow_list_staff', views.borrow_list_staff, name='borrow_list_staff'),

    path('borrow/create/', views.borrow_new, name='borrow_new'),
    path('borrow_staff/create/', views.borrow_new_staff, name='borrow_new_staff'),

    path('borrow/<int:pk>/edit/', views.borrow_edit, name='borrow_edit'),
    path('borrow_staff/<int:pk>/edit/', views.borrow_edit_staff, name='borrow_edit_staff'),

    path('borrow/<int:pk>/delete/', views.borrow_delete, name='borrow_delete'),
    path('borrow_staff/<int:pk>/delete/', views.borrow_delete_staff, name='borrow_delete_staff'),

    path('book_list', views.book_list, name='book_list'),
    path('book_list_staff', views.book_list_staff, name='book_list_staff'),

    path('book/create/', views.book_new, name='book_new'),
    path('book_staff/create/', views.book_new_staff, name='book_new_staff'),

    path('book/<int:pk>/edit/', views.book_edit, name='book_edit'),
    path('book_staff/<int:pk>/edit/', views.book_edit_staff, name='book_edit_staff'),

    path('book/<int:pk>/delete/', views.book_delete, name='book_delete'),
    path('book_staff/<int:pk>/delete/', views.book_delete_staff, name='book_delete_staff'),

    path('pdf/', views.borrow_summary_pdf,name='borrow_summary_pdf'),

    #path('borrow_summary_pdf', views.borrow_summary_pdf, name='borrow_summary_pdf'),

    #path('borrow_summary_pdf', views.get, name='borrow_summary_pdf'),
]

myclm/forms.py
from django import forms
from .models import Member,Borrow,Book
from .models import User

class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True)

class SignUpForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user = User.objects.filter(email__iexact=email).first()
        if user:
            if user.is_staff:
                user_role = "Staff"

            else:
                user_role = "Member"
            raise forms.ValidationError(
                "{} with this email already exists, use another email.".format(
                    user_role
                )
            )
        return email

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if len(password) < 6:
            raise forms.ValidationError("Password should be minimum 6 characters long")

        if password != self.data.get("confirm_password"):
            raise forms.ValidationError("Passwords do not match")
        return password

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('Member_NUID','Member_first_name','Member_middle_name', 'Member_last_name','Member_organization','Member_role','Member_email', 'Member_address', 'Member_city', 'Member_state', 'Member_zipcode', 'Member_phone')

class BorrowForm(forms.ModelForm):
   class Meta:
       model = Borrow
       fields = ('Borrow_Member_NUID', 'Borrow_Book_Name', 'Borrow_Author_Name', 'Borrow_Category_Name', 'Taken_date', 'Broughtback_date' )

class BookForm(forms.ModelForm):
   class Meta:
       model = Book
       fields = ('Book_Title', 'Book_ISBN', 'Book_publisher', 'Book_author_name', 'Book_category_name')

myclm/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm,UserCreationForm
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse, HttpResponseRedirect, reverse
from .models import *
from .forms import *
from django.contrib.auth import authenticate, login, logout
from myclm.access_decorators_mixins import member_access_required, staff_access_required


# Create your views here.
def staffSignup(request):
    if request.method == "GET":
        return render(request, "myclm/staff_signup.html", {})

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = User.objects.create(
                email=form.cleaned_data.get("email"),
                username=form.cleaned_data.get("email"),
                is_staff=True, role='staff'
            )
            user.set_password(form.cleaned_data.get("password"))
            user.save()
            login(request, user)
            return redirect(reverse("myclm:home_staff",))
        else:
            return render(
                request, "myclm/staff_signup.html", {"errors": form.errors}
            )


def memberSignup(request):
    if request.method == "GET":
        return render(request, "myclm/member_signup.html", {})

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = User.objects.create(
                email=form.cleaned_data.get("email"),
                username=form.cleaned_data.get("email"),
                is_member=True, role="member",
            )
            user.set_password(form.cleaned_data.get("password"))
            user.save()
            login(request, user)
            return redirect(reverse("myclm:home_member",))
        else:
            return render(
                request, "myclm/member_signup.html", {"errors": form.errors}
            )


def memberLogin(request):
    if request.method == "GET":
        return render(request, "myclm/member_login.html", {})

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(username=email, password=password,)
            if user is None:
                return render(
                    request,
                    "myclm/member_login.html",
                    {"errors": {"account_error": ["Invalid email or password"]}},
                )

            elif user is not None:
                if user.is_active and user.is_member:
                    login(request, user)
                    return HttpResponseRedirect(reverse("myclm:home_member",))
                elif user.is_active and user.is_member is False:
                    return render(
                        request,
                        "myclm/member_login.html",
                        {
                            "errors": {
                                "account_error": ["Email is not associated with Mentor"]
                            }
                        },
                    )

                else:
                    return HttpResponse(
                        "# your account is inactive contact admin for details user@example.com"
                    )

            else:
                pass
        else:
            return render(request, "myclm/member_login.html", {"errors": form.errors})


def staffLogin(request):
    if request.method == "GET":
        return render(request, "myclm/staff_login.html", {})

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(username=email, password=password,)
            if user is None:
                return render(
                    request,
                    "myclm/staff_login.html",
                    {"errors": {"account_error": ["Invalid email or password"]}},
                )

            elif user is not None:
                if user.is_active and user.is_staff:
                    login(request, user)
                    return HttpResponseRedirect(reverse("myclm:home_staff",))
                elif user.is_active and user.is_member is False:
                    return render(
                        request,
                        "myclm/staff_login.html",
                        {
                            "errors": {
                                "account_error": ["Email is not associated with Staff"]
                            }
                        },
                    )

                else:
                    return HttpResponse(
                        "# your account is inactive contact admin for details user@example.com"
                    )

            else:
                pass
        else:
            return render(request, "myclm/staff_login.html", {"errors": form.errors})


def change_password(request):
    form = PasswordChangeForm(user=request.user, data=request.POST)
    if request.method == 'GET':
        return render(request, "myclm/password_change_form.html", {"form": form})
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return render(
                request, "myclm/password_change_done.html", {}
            )
        return render(
            request, "myclm/password_change_form.html", {"errors": form.errors}
        )



def homepage(request):
    print('yessss')
    # return HttpResponse("test myclm")
    return render(request, "myclm/landing_page.html", {})
    #return render(request, "myclm/home_member.html", {})

# Create your views here.
now = timezone.now()
def home(request):
   return render(request, 'myclm/home.html',
                 {'myclm': home})

def home_member(request):
   return render(request, 'myclm/home_member.html',
                 {'myclm': home_member})

def home_staff(request):
   return render(request, 'myclm/home_staff.html',
                 {'myclm': home_staff})

def user_logout(request):
    logout(request)
    return redirect(reverse("myclm:homepage"))

@login_required
def member_list(request):
    member = Member.objects.filter(created_date__lte=timezone.now())
    return render(request, 'myclm/member_list.html',
                 {'members': member})

@login_required
def member_list_staff(request):
    member = Member.objects.filter(created_date__lte=timezone.now())
    return render(request, 'myclm/member_list_staff.html',
                 {'members': member})

@login_required
def member_edit(request, pk):
   member = get_object_or_404(Member, pk=pk)
   if request.method == "POST":
       # update
       form = MemberForm(request.POST, instance=member)
       if form.is_valid():
           member = form.save(commit=False)
           member.updated_date = timezone.now()
           member.save()
           member = Member.objects.filter(created_date__lte=timezone.now())
           return render(request, 'myclm/member_list.html',
                         {'members': member})
   else:
        # edit
       form = MemberForm(instance=member)
   return render(request, 'myclm/member_edit.html', {'form': form})

@login_required
def member_edit_staff(request, pk):
   member = get_object_or_404(Member, pk=pk)
   if request.method == "POST":
       # update
       form = MemberForm(request.POST, instance=member)
       if form.is_valid():
           member = form.save(commit=False)
           member.updated_date = timezone.now()
           member.save()
           member = Member.objects.filter(created_date__lte=timezone.now())
           return render(request, 'myclm/member_list_staff.html',
                         {'members': member})
   else:
        # edit
       form = MemberForm(instance=member)
   return render(request, 'myclm/member_edit_staff.html', {'form': form})


@login_required
def member_delete(request, pk):
   member = get_object_or_404(Member, pk=pk)
   member.delete()
   return redirect('myclm:member_list')

@login_required
def member_delete_staff(request, pk):
   member = get_object_or_404(Member, pk=pk)
   member.delete()
   return redirect('myclm:member_list_staff')

@login_required
def member_new_staff(request):
   if request.method == "POST":
       form = MemberForm(request.POST)
       if form.is_valid():
           member = form.save(commit=False)
           member.created_date = timezone.now()
           member.save()
           members = Member.objects.filter(created_date__lte=timezone.now())
           return render(request, 'myclm/member_list_staff.html',
                         {'members': members})
   else:
       form = MemberForm()
       # print("Else")
   return render(request, 'myclm/member_new_staff.html', {'form': form})

@login_required
def borrow_list(request):
   borrows = Borrow.objects.filter(created_date__lte=timezone.now())
   return render(request, 'myclm/borrow_list.html', {'borrows': borrows})

@login_required
def borrow_list_staff(request):
   borrows = Borrow.objects.filter(created_date__lte=timezone.now())
   return render(request, 'myclm/borrow_list_staff.html', {'borrows': borrows})

@login_required
def borrow_new(request):
   if request.method == "POST":
       form = BorrowForm(request.POST)
       if form.is_valid():
           borrow = form.save(commit=False)
           borrow.created_date = timezone.now()
           borrow.save()
           borrows = Borrow.objects.filter(created_date__lte=timezone.now())
           return render(request, 'myclm/borrow_list.html',
                         {'borrows': borrows})
   else:
       form = BorrowForm()
       # print("Else")
   return render(request, 'myclm/borrow_new.html', {'form': form})

@login_required
def borrow_new_staff(request):
   if request.method == "POST":

myclm/templates/myclm/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<html lang="en">
<head>
    <title>College Library Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #ff2514;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #ffa500;
            color: #ff3a29;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="">
                College Library Services
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'myclm:home' %}">Home</a></li>


            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'myclm:user_logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <!--<li><a href="{% url 'myclm:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li> -->
                {% endif %}
            </ul>
        </div>
    </div>

</nav>
<h1 align="center">College Library Services</h1>
<div class="content container">
    <div class="row">
        <div class="col-md-20">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-5">
                            <div class="thumbnail" >

                                <img src="{% static "images/member_login.jpg" %}" alt="Member"/>
                                <div class="caption">
                                    <h2></h2>
                                       <td><a  class="btn btn-primary" href="{% url 'myclm:memberLogin' %}"
                                              role="button">Login</a></td>


                                     <p class="text-left mt-3">Don't have an account?
                                            <a href="{% url 'myclm:memberSignup' %}">Sign Up Now</a>
                                        </p>
                                        <p class="text-left mt-3">

                                        </p>
                                        <p class="text-left mt-3">
                                            <a href="{% url 'password_reset' %}">Forgot Password?</a>
                                        </p>


                                </div>

                        </div>
                        </div>
                        <div class="col-md-5">
                            <div class="thumbnail">
                                <img src="{% static "images/staff_login.jpg" %}" alt="Book"/>
                                <div class="caption">
                                    <h2></h2>
                                   <!-- <p>High quality Books at affordable prices.</p> -->
                                        <td><a class="btn btn-primary" href="{% url 'myclm:staffLogin' %}"
                                              role="button">Login</a></td>

                                        <p class="text-center mt-3">

                                        </p>
                                         <p class="text-left mt-3">
                                          Don't have an account?
                                          <a href="{% url 'myclm:staffSignup' %}">Sign Up Now</a>
                                        </p>
                                        <p class="text-left mt-3">
                                          <a href="{% url 'password_reset' %}">Forgot Password?</a>
                                        </p>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

myclm/templates/myclm/book_delete.html
{% extends 'myclm/base_member.html' %}
{% block body_block %}
    <h1>Delete {{ book.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'myclm:home' pk=borrow.borrow_NUID %} ">Cancel</a>

    </form>

{% endblock %}

myclm/templates/myclm/book_delete_staff.html
{% extends 'myclm/base_staff.html' %}
{% block body_block %}
    <h1>Delete {{ book.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'myclm:home' pk=book.book_name %} ">Cancel</a>

    </form>

{% endblock %}

myclm/templates/myclm/book_edit.html
{% extends 'myclm/base_member.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Book</h1>
    <form method="POST" class="borrow-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

myclm/templates/myclm/book_new.html
{% extends 'myclm/base_member.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add Book</h1>
    <form method="POST" class="book-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

myclm/templates/myclm/borrow_delete.html
{% extends 'myclm/base_member.html' %}
{% block body_block %}
    <h1>Delete {{ borrow.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'myclm:home' pk=borrow.borrow_NUID %} ">Cancel</a>

    </form>

{% endblock %}

myclm/templates/myclm/home.html
{% extends 'myclm/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% block content %}

   <body>
    <html>
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                 <div class="col-md-5">
                            <div class="thumbnail" >
                                <img src="{% static "images/member_login.jpg" %}" alt="Member"/>
                                <div class="caption">
                                    <h2></h2>
                                       <td><a  class="btn btn-default" href="{% url 'myclm:memberLogin' %}"
                                              role="button">Login</a></td>


                                     <p class="text-left mt-3">Don't have an account
                                            <a href="{% url 'myclm:memberSignup' %}">Sign Up Now</a>
                                        </p>
                                        <p class="text-left mt-3">

                                        </p>
                                        <p class="text-left mt-3">
                                            <a href="{% url 'password_reset' %}">Forgot Password?</a>
                                        </p>


                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="thumbnail">
                                <img src="{% static "images/staff_login.jpg" %}" alt="Book"/>
                                <div class="caption">
                                    <h2></h2>
                                   <!-- <p>High quality Books at affordable prices.</p> -->
                                        <td><a class="btn btn-default" href="{% url 'myclm:staffLogin' %}"
                                              role="button">Login</a></td>

                                        <p class="text-center mt-3">

                                        </p>
                                         <p class="text-left mt-3">
                                          Don't have an account
                                          <a href="{% url 'myclm:staffSignup' %}">Sign Up Now</a>
                                        </p>
                                        <p class="text-left mt-3">
                                          Forgot password?
                                          <a href="{% url 'password_reset' %}">Reset Password</a>
                                        </p>
                                </div>
                            </div>
                        </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
    </html>
{% endblock %}

myclm/templates/myclm/member_delete_staff.html
{% extends 'myclm/base_member.html' %}
{% block body_block %}
    <h1>Delete {{ member.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'myclm:home' pk=member.member_NUID %} ">Cancel</a>

    </form>

{% endblock %}

myclm/templates/myclm/member_list.html
{% extends 'myclm/base_member.html' %}
 {% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>College Library Management</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        College Library Services
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Member Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Member NUID</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Organization</th>
                <th>Role</th>
                <th>Email</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>
                <th>Phone</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for member in members %}
                <tr>
                    <td>{{ member.Member_NUID }}</td>
                    <td>{{ member.Member_first_name }}</td>
                    <td>{{ member.Member_middle_name }}</td>
                    <td>{{ member.Member_last_name }}</td>
                    <td>{{ member.Member_organization }}</td>
                    <td>{{ member.Member_role }}</td>
                    <td>{{ member.Member_email }}</td>
                    <td>{{ member.Member_address }}</td>
                    <td>{{ member.Member_city }}</td>
                    <td>{{ member.Member_state }}</td>
                    <td>{{ member.Member_zipcode }}</td>
                    <td>{{ member.Member_phone }}</td>
                    <td><a href="{% url 'myclm:member_edit' pk=member.pk %}" class="btn btn-warning">Edit</a>


                    <td><a href="{% url 'myclm:member_delete' pk=member.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                    </td>
                    <!-- <td><a href="" class="btn btn-primary">Summary</a> -->

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

myclm/templates/myclm/member_signup.html
{% extends 'myclm/base.html' %}
{% block content %}
<h2 class="text-center">
  Member SignUp
</h2>
<div class="row justify-content-center align-items-center">
  <div class="col-xs-6 col-md-6 col-lg-5 col-xl-5 custom-card" style="padding: 2em;">

    <form method="POST">
      <div class="form-group">
        {% csrf_token %}
        <label for="exampleInputEmail1">Email address <span style="color: red;">*</span></label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
          placeholder="user@example.com" name="email" value="{{request.POST.email}}">
        <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->

        {% if errors and errors.email %}
        {% for error in errors.email %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        {% endif %}
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password <span style="color: red;">*</span></label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
        {% if errors and errors.password %}
        {% for error in errors.password %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        {% endif %}
      </div>
      <div class="form-group">
        <label for="exampleInputPassword2">Confirm Password <span style="color: red;">*</span></label>
        <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password"
          name="confirm_password">
        {% if errors and errors.confirm_password %}
        {% for error in errors.confirm_password %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        {% endif %}
      </div>
      <div class="col-md-6 mx-auto text-center">
      <button type="submit" class="btn btn-primary btn-block" >Register</button>
      
      </div>
    </form>
   <p class="text-center mt-3">Already have an account <a href="{% url 'myclm:memberLogin' %}">Sign In</a> </p>
  </div>
</div>

{% endblock content %}